obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.2,0.2], [0.2,0.2], [0.2,-0.2], [-0.2,-0.2]]
inflation_radius: 0.1

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {
  sensor_frame: lidar_link,
  data_type: LaserScan,
  topic: /lidar/laser,
  marking: true,
  clearing: true
  }

point_cloud_sensor: {
  sensor_frame: camera_link_optical,
  data_type: PointCloud,
  topic: /camera/depth/points,
  marking: true,
  clearing: true
  }
